### ISSUE TITLE
Latest version won't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by Kilian** [electron/fiddle#144]
electron-fiddle immediately closes with the following error:
```
$ electron-fiddle 
Creating main window
(node:18671) UnhandledPromiseRejectionWarning: Error: Cannot find module '../clipboard'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/usr/lib/electron-fiddle/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as clipboard] (/usr/lib/electron-fiddle/resources/electron.asar/common/api/exports/electron.js:9:18)
    at Object.__importStar (/usr/lib/electron-fiddle/resources/app.asar/node_modules/tslib/tslib.js:215:100)
    at Object.parcelRequire.src/constants.ts (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:692:32)
    at newRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:49:24)
    at localRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:55:14)
(node:18671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So it seems the clipboard import isn't properly included?

**Comment by malept** [comment]
Very strange, I'm able to download/install/run Electron Fiddle 0.4.1's `.deb` just fine on Debian Stretch.

**Comment by sfsfco** [comment]
same issue on Ubuntu 18.04

**Comment by felixrieseberg** [comment]
Hm, interesting. @Kilian, @sfsfco: You're running Fiddle 0.4.1?

**Comment by Kilian** [comment]
Yes, installed via .deb.

**Comment by felixrieseberg** [comment]
Thanks! 🤔 This is super weird, because this is Electron-internal code giving us trouble here. I'll try to repro this in my Linux box.

**Comment by felixrieseberg** [comment]
I _hope_ that things are fixed with 0.5. Please reopen if they're not!

**Comment by Kilian** [comment]
Sorry, but 0.4.2 through 0.5.1 don't work still.

0.4.2 gives this error:
```
[kilian:~]$ electron-fiddle                
Creating main window
(node:28998) UnhandledPromiseRejectionWarning: Error: Cannot find module 'electron-default-menu'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/usr/lib/electron-fiddle/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at newRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:36:18)
    at newRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:23:18)
    at localRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:55:14)
    at setupMenu (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:1097:23)
    at App.onReady (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:1187:3)
(node:28998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

0.5.0 and 0.5.1 both just immediately quit without any logging to the console.

**Comment by Kilian** [comment]
Sorry, but the deb files of 0.4.2 through 0.5.1 don't work still.

0.4.2 gives this error:
```
[kilian:~]$ electron-fiddle                
Creating main window
(node:28998) UnhandledPromiseRejectionWarning: Error: Cannot find module 'electron-default-menu'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/usr/lib/electron-fiddle/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at newRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:36:18)
    at newRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:23:18)
    at localRequire (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:55:14)
    at setupMenu (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:1097:23)
    at App.onReady (/usr/lib/electron-fiddle/resources/app.asar/dist/src/main/main.js:1187:3)
(node:28998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

0.5.0 and 0.5.1 both just immediately quit without any logging to the console.
