### ISSUE TITLE
Intermittent Coveralls failures on CI

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#449]
### Problem

Coveralls will frequently fail on CI, leading to blocked pull requests. This seems to be an upstream issue that we've been dealing with for the last few months.

Ref https://github.com/lemurheavy/coveralls-public/issues/1427
Ref https://github.com/lemurheavy/coveralls-public/issues/750

This error will look something like this in the TravisCI logs:
```shell
0.46s$ if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run test:coverage; fi
> electron-fiddle@0.15.1 test:coverage /home/travis/build/electron/fiddle
> cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
[error] "2020-07-27T00:17:32.111Z"  'error from getOptions'
/home/travis/build/electron/fiddle/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Error: Command failed: git cat-file -p f540f5d7d65076553db0c902506d2945b3d1b09b
fatal: Not a valid object name f540f5d7d65076553db0c902506d2945b3d1b09b
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git cat-file -p f540f5d7d65076553db0c902506d2945b3d1b09b'
}
```

### Workaround

If your PR fails, you can force-push to re-trigger the build.

```shell
git checkout my-failing-branch
git commit --amend # no changes needed to the message; this is just to change the commit hash
git push --force-with-lease
```

Note that these steps don't guarantee that Coveralls will pass. You might need to repeat a few times to get a pass.

**Comment by erickzhao** [comment]
We switched to GitHub Actions in https://github.com/electron/fiddle/pull/504 and haven't encountered the failure in the last month or so. Will close this issue for now.
