### ISSUE TITLE
Poor version selection experience for `darwin-arm64` binaries

### ISSUE THREAD

**Issue by nikolasrieble** [electron/fiddle#823]
Downloading version 10.x.x is broken. The download seemingly never starts 

<img width="381" alt="Screenshot 2021-08-02 at 19 56 41" src="https://user-images.githubusercontent.com/27995606/127904043-1cdf4000-5dc2-49ed-8db2-f33d8e26a1a4.png">

and then stays in the state `Downloading`

<img width="350" alt="Screenshot 2021-08-02 at 19 59 33" src="https://user-images.githubusercontent.com/27995606/127904191-c45b22af-4ec7-4821-9f29-07538d0e2677.png">

The download works quick and easy for version since (including) 11.0.0

**Comment by ckerr** [comment]
Hey @nikolasrieble, I just gave this a try in 0.26.0 and downloading 10.x.x is working here; tried with 10.0.0 and 10.4.7.

My first thought is maybe this was a temporary CDN hiccup. Is 10.x.x still failing to download for you? And if so, could you provide

- Electron Fiddle version
- The console.log from devtools?

Thanks!

**Comment by nikolasrieble** [comment]
@ckerr It is still failing.
Sure, happy to provide both: 

> Version 0.26.0 (12.0.14)

Console log from devtools:

> State: Downloading Electron 10.0.0-beta.3
instrument.ts:129 Binary: Downloading Electron 10.0.0-beta.3
instrument.ts:129 Binary: Version 10.0.0-beta.3 download progress: 0
instrument.ts:129 Binary: Version 10.0.0-beta.3 download progress: 1
main.99d03ea8.js:56 Uncaught (in promise) HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.0.0-beta.3/electron-v10.0.0-beta.3-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Applications/Electron Fiddle.app/Contents/Resources/app.asar/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:315:20)
    at module.exports (/Applications/Electron Fiddle.app/Contents/Resources/app.asar/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Applications/Electron Fiddle.app/Contents/Resources/app.asar/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Applications/Electron Fiddle.app/Contents/Resources/app.asar/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by malept** [comment]
`darwin/arm64` builds were introduced with Electron 11 per the [blog](https://www.electronjs.org/blog/apple-silicon).

@ckerr Electron Packager has a bunch of logic around [what are the official platform/arch combinations and when they became available](https://github.com/electron/electron-packager/blob/cb7238f7c9261f2f1fca3d81e786d9c49d111119/src/targets.js#L7-L30). I wonder if this actually needs to live in `@electron/get`?

**Comment by dsanders11** [comment]
Closing this as we disabled downloads of pre-11.0.0 versions on Apple Silicon in #1019.
