### ISSUE TITLE
I also tested it using V14.17.4 in windows server 2016. but it still failed with following error:

### ISSUE THREAD

**Issue by Ttamez68A** [electron/fiddle#955]
I also tested it using V14.17.4 in windows server 2016. but it still failed with following error:
node -v
v14.17.4
>bf orchestrator:basemodel:list
Error: The specified module could not be found.
> //?/C:/Users/i_tsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core# /- [ orchestrator-core.nod
```
    at Module.patchedRequire [as require] (C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (C:/Users/itsp/AppData/Roaming/npm/node_modules/@[microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

- # _Originally posted by @hanhsia]( i~~ https://github.com/microsoft/botframework-cli/issues/1326#issuecomment-1008604505_

**Comment by erickzhao** [comment]
What version of Electron Fiddle are you using? Older versions might have had a bug where namespaced NPM modules were unable to be installed.
